"""Add worker_id and heartbeat_at to task_state

Revision ID: f51e5481fdc1
Revises: fd166328014a
Create Date: 2026-04-13 13:03:48.066352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51e5481fdc1'
down_revision: Union[str, None] = 'fd166328014a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_state', sa.Column('worker_id', sa.String(length=64), nullable=True))
    op.add_column('task_state', sa.Column('heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_index(op.f('ix_task_state_worker_id'), 'task_state', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_state_worker_id'), table_name='task_state')
    op.drop_column('task_state', 'heartbeat_at')
    op.drop_column('task_state', 'worker_id')
    # ### end Alembic commands ###
