"""v3 initial schema

Revision ID: fd166328014a
Revises: 
Create Date: 2026-04-13 11:10:43.250782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd166328014a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('wave', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_agent_id'), 'event_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_log_task_id'), 'event_log', ['task_id'], unique=False)
    op.create_index(op.f('ix_event_log_ts'), 'event_log', ['ts'], unique=False)
    op.create_table('quarantine',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('scheduler_meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('task_state',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('story_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('passes', sa.Boolean(), nullable=False),
    sa.Column('wave', sa.Integer(), nullable=False),
    sa.Column('original_wave', sa.Integer(), nullable=True),
    sa.Column('scheduled_wave', sa.Integer(), nullable=True),
    sa.Column('rescheduled_from', sa.Integer(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('ai_log_ref', sa.Text(), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_state_passes'), 'task_state', ['passes'], unique=False)
    op.create_index('ix_task_state_passes_wave', 'task_state', ['passes', 'wave'], unique=False)
    op.create_index(op.f('ix_task_state_status'), 'task_state', ['status'], unique=False)
    op.create_index('ix_task_state_status_wave', 'task_state', ['status', 'wave'], unique=False)
    op.create_index(op.f('ix_task_state_wave'), 'task_state', ['wave'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_state_wave'), table_name='task_state')
    op.drop_index('ix_task_state_status_wave', table_name='task_state')
    op.drop_index(op.f('ix_task_state_status'), table_name='task_state')
    op.drop_index('ix_task_state_passes_wave', table_name='task_state')
    op.drop_index(op.f('ix_task_state_passes'), table_name='task_state')
    op.drop_table('task_state')
    op.drop_table('scheduler_meta')
    op.drop_table('quarantine')
    op.drop_index(op.f('ix_event_log_ts'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_task_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_agent_id'), table_name='event_log')
    op.drop_table('event_log')
    # ### end Alembic commands ###
